// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwy5Y6KmBaSQqNr_bdpMcULJkU5Euv5-Y',
    appId: '1:907618415879:android:7cf840c8554c97b55fc1a2',
    messagingSenderId: '907618415879',
    projectId: 'wechat-10f8b',
    storageBucket: 'wechat-10f8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKm3U12ylPKvNBKqR2glcUwstya8a3Z3c',
    appId: '1:907618415879:ios:a1dad1336747a4965fc1a2',
    messagingSenderId: '907618415879',
    projectId: 'wechat-10f8b',
    storageBucket: 'wechat-10f8b.appspot.com',
    androidClientId: '907618415879-50fu16taglkpv6kgfg7dkm36lb6dhpuj.apps.googleusercontent.com',
    iosClientId: '907618415879-apeigl2a33o7atu2bceihj6lvat37rgo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chattingApp',
  );
}
